version: "3"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

  web:
    # build: .docker1
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MAGIC_NAME = CAT
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "statr"]
